Imported Upstream version 0.9.10+dfsg~1

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,25 +1,32 @@
 #!/bin/bash
 
-
 if [ "$1" = "-h" -o "$1" = "--help" -o "$1" = "-help" ]; then
-    echo "** valid options:"
-    echo "  --with_gtk3     : compile with GTK+ 3.x"
-    echo "  --use_xim=N     : disable the support of XIM"
-    echo "  --prefix=path   : install prefix (e.g. /usr)"
-#   TODO fix not working option(s)
-#   echo "  --use_tray=N    : disable system tray"
-    echo "  --use_unity=N   : disable Ubuntu unity tray"
-    echo "  --use_i18n=N    : disable i18n"
-    echo "  --use_tsin=N    : disable Tsin input method"
-    echo "  --use_anthy=N   : disable Anthy input method"
-    echo "  --use_chewing=N : disable Chewing input method"
-    echo "  --use_qt3=Y     : enable Qt 3.x immodule"
-    echo "  --use_qt4=N     : disable Qt 4.x immodule"
-    echo "  --qt3-moc-path  : specify the path of \"moc\" tool for Qt 3.x"
-    echo "  --qt4-moc-path  : specify the path of \"moc\" tool for Qt 4.x"
-    echo "  --qt4-install-to: install path for Qt 4.x input method plugin."
-    echo "  --use_gtk=N     : disable GTK+ 2.x immodule"
-    echo "  --use_gtk3=N    : disable GTK+ 3.x immodule"
+    echo "Usage: $0 [OPTION]... [VAR=VALUE]..."
+    echo ""
+    echo "Installation directories:"
+    echo "  --prefix=PREFIX       : install in PREFIX (e.g. /usr) [default: /usr/local]"
+    echo ""
+    echo "Optional Packages:"
+    echo "  --with-gtk=2.0|3.0    : which gtk+ version to compile against [default: 2.0]"
+    echo ""
+    echo "Optional Features:"
+    echo "  --disable-nls            : disable Native Language Support [default: enable]"
+    echo "  --disable-xim            : disable the support of XIM [default: enable]"
+    echo "  --disable-system-tray    : disable system tray support [default: enable]"
+    echo "  --disable-tsin           : disable Tsin input method [default: enable]"
+    echo "  --disable-gtk2-im-module : disable GTK+ 2.x im-module [default: auto-detect]"
+    echo "  --disable-gtk3-im-module : disable GTK+ 3.x im-module [default: auto-detect]"
+    echo "  --enable-qt3-immodule    : enable QT3 im-module [default: disable]"
+    echo "  --disable-qt4-immodule   : disable QT4 im-module [default: auto-detect]"
+    echo "  --disable-anthy          : disable Anthy input method [default: auto-detect]"
+    echo "  --disable-chewing        : disable Chewing input method [default: auto-detect]"
+    echo "  --disable-appindicator   : disable Ubuntu unity tray [default: auto-detect]"
+    echo ""
+    echo "System Specific Pathes:"
+    echo "  --qt3-moc-path=PATH       : specify the path of \"moc\" command for Qt 3.x"
+    echo "  --qt4-moc-path=PATH       : specify the path of \"moc\" command for Qt 4.x"
+    echo "  --qt4-im-module-path=PATH : specify the install path for Qt 4.x im-module."
+    echo ""
     exit
 fi
 
@@ -41,7 +48,7 @@ if [ $? = 0 ]; then
   FREEBSD=1
 fi
 
-SO_FLAGS="-shared"
+SO_FLAGS="-shared -Wl,--as-needed"
 MAC_OS=0
 uname | grep Darwin > /dev/null 2> /dev/null
 if [ $? = 0 ]; then
@@ -98,63 +105,123 @@ if [ "$HIME_USE_XIM" ]; then
   use_xim=$HIME_USE_XIM
 fi
 
+QT4_IM_DIR_CUSTOM=
 for opt do
   case "$opt" in
-  --with_gtk3) GTK=gtk+-3.0
+  --with_gtk3|--with-gtk=3.0) GTK=gtk+-3.0
   ;;
   --prefix=*) prefix=`echo $opt | cut -d '=' -f 2`
   ;;
   --use_xim=*) use_xim=`echo $opt | cut -d '=' -f 2`
   ;;
+  --enable-xim) use_xim=Y
+  ;;
+  --disable-xim) use_xim=N
+  ;;
   --use_tray=*) use_tray=`echo $opt | cut -d '=' -f 2`
+  ;;
+  --enable-system-tray) use_tray=Y
+  ;;
+  --disable-system-tray) use_tray=N
   ;;
   --use_unity=*) use_unity=`echo $opt | cut -d '=' -f 2`
   ;;
+  --enable-appindicator) use_unity=Y
+  ;;
+  --disable-appindicator) use_unity=N
+  ;;
   --use_i18n=*) use_i18n=`echo $opt | cut -d '=' -f 2`
+  ;;
+  --enable-nls) use_i18n=Y
+  ;;
+  --disable-nls) use_i18n=N
   ;;
   --use_tsin=*) use_tsin=`echo $opt | cut -d '=' -f 2`
   ;;
+  --enable-tsin) use_tsin=Y
+  ;;
+  --disable-tsin) use_tsin=N
+  ;;
   --use_anthy=*) use_anthy=`echo $opt | cut -d '=' -f 2`
+  ;;
+  --enable-anthy) use_anthy=Y
+  ;;
+  --disable-anthy) use_anthy=N
   ;;
   --use_chewing=*) use_chewing=`echo $opt | cut -d '=' -f 2`
   ;;
+  --enable-chewing) use_chewing=Y
+  ;;
+  --disable-chewing) use_chewing=N
+  ;;
   --use_qt3=*) use_qt3=`echo $opt | cut -d '=' -f 2`
+  ;;
+  --enable-qt3-immodule) use_qt3=Y
+  ;;
+  --disable-qt3-immodule) use_qt3=N
   ;;
   --use_qt4=*) use_qt4=`echo $opt | cut -d '=' -f 2`
   ;;
+  --enable-qt4-immodule) use_qt4=Y
+  ;;
+  --disable-qt4-immodule) use_qt4=N
+  ;;
   --use_gtk=*) use_gtk=`echo $opt | cut -d '=' -f 2`
   ;;
+  --enable-gtk2-im-module) use_gtk=Y
+  ;;
+  --disable-gtk2-im-module) use_gtk=N
+  ;;
   --use_gtk3=*) use_gtk3=`echo $opt | cut -d '=' -f 2`
+  ;;
+  --enable-gtk3-im-module) use_gtk3=Y
+  ;;
+  --disable-gtk3-im-module) use_gtk3=N
   ;;
   --qt3-moc-path=*) QT3_MOC_PATH=`echo $opt | cut -d '=' -f 2`
   ;;
   --qt4-moc-path=*) QT4_MOC_PATH=`echo $opt | cut -d '=' -f 2`
   ;;
-  --qt4-install-to=*) QT4_IM_DIR=`echo $opt | cut -d '=' -f 2`
+  --qt4-install-to=*|--qt4-im-module-path=*) QT4_IM_DIR_CUSTOM=`echo $opt | cut -d '=' -f 2`
   ;;
   esac
 done
 
 echo "prefix: $prefix"
 
+echo -n ".... Testing Xtst        :  "
+XTST=`pkg-config --exists xtst 2> /dev/null`
+if [ $? != 0 ]; then
+  echo "please install rpm/package xtest-devel. abort!"
+  exit 1
+else
+  echo "found."
+fi
+
 if [ -z "$GTK" ]; then
   GTK=gtk+-2.0
 fi
 
-echo -n ".... Testing $GTK    : "
+echo -n ".... Testing $GTK    :  "
 
-GTKINC=`pkg-config --cflags $GTK`
+GTKINC=`pkg-config --cflags $GTK 2> /dev/null`
 
 if [ $? != 0 ]; then
-  GTK=gtk+-3.0
-  echo -n ".... Testing $GTK : "
+  if [ "$GTK" = gtk+-2.0 ]; then
+    echo "not found, trying gtk+-3.0..."
+    GTK=gtk+-3.0
+    echo -n ".... Testing $GTK    :  "
   
-  GTKINC=`pkg-config --cflags $GTK`
-  
-  if [ $? != 0 ]; then
-    echo "$GTK or above required --cflags"
+    GTKINC=`pkg-config --cflags $GTK 2> /dev/null`
+    if [ $? != 0 ]; then
+      echo "$GTK or above required --cflags. abort!"
+      rm -f config.mak
+      exit 1
+    fi
+  else
+    echo "$GTK or above required --cflags. abort!"
     rm -f config.mak
-    exit -1;
+    exit 1
   fi
 fi
 
@@ -178,15 +245,23 @@ if [ ! -x /bin/bash ]; then
 fi
 
 
-GTKLDFLAGS=`pkg-config --libs $GTK`
+GTKLDFLAGS=`pkg-config --libs $GTK 2> /dev/null`
 
 if [ $? != 0 ]; then
   echo "$GTK or above required --libs"
-  echo "please install rpm/package libgtk+2.0_0-devel"
+  echo "please install rpm/package libgtk+2.0_0-devel/libgtk+3.0_0-devel. abort!"
   rm -f config.mak
-  exit -1;
+  exit 1
 else
-  echo " found."
+  echo "found."
+fi
+
+if [ "$GTK" = gtk+-2.0 ]; then
+  pkg-config --exists 'gtk+-2.0 >= 2.10' 2> /dev/null
+  if [ $? != 0 ]; then
+    echo ".... Testing system-tray :  disabled. gtk > 2.10 is needed to enable system-tray."
+    use_tray=N
+  fi
 fi
 
 echo -n ".... Testing anthy       :  "
@@ -214,18 +289,25 @@ else
     USE_CHEWING='N'
     echo "disabled."
   else
-    USE_CHEWING='Y'
-    echo "found."
+    pkg-config --exists 'chewing >= 0.3.2' 2> /dev/null
+    if [ $? != 0 ]; then
+      USE_CHEWING='N'
+      echo "disabled. chewing > 0.3.2 is needed to enable chewing."
+    else
+      USE_CHEWING='Y'
+      echo "found."
+    fi
   fi
 fi
 
+if [ "$GTK" = "gtk+-3.0" ]; then
+  APPINDICATOR=appindicator3-0.1
+else
+  APPINDICATOR=appindicator-0.1
+fi
 if [ "$use_unity" = "Y" ]; then
   echo -n ".... Testing appindicator:  "
-  if [ "$GTK" = "gtk+-3.0" ]; then
-    USE_UNITY=`pkg-config --libs appindicator3-0.1 2> /dev/null`
-  else
-    USE_UNITY=`pkg-config --libs appindicator-0.1 2> /dev/null`
-  fi
+  USE_UNITY=`pkg-config --libs $APPINDICATOR 2> /dev/null`
   if [ $? != 0 ]; then
     echo not found, unity tray is turned off.
     USE_UNITY=N
@@ -234,15 +316,16 @@ if [ "$use_unity" = "Y" ]; then
       USE_UNITY='N'
       echo "disabled."
     else
-      USE_UNITY='Y'
-      echo "found."
-      UNITY_INC="-I/usr/include/libappindicator-0.1"
-      if [ "$GTK" = "gtk+-3.0" ]; then
-        GTKINC=`pkg-config --cflags $GTK appindicator3-0.1`
-        GTKLDFLAGS=`pkg-config --libs $GTK appindicator3-0.1`
+      pkg-config --exists "$APPINDICATOR >= 0.4.0" 2> /dev/null
+      if [ $? != 0 ]; then
+        echo "disabled. appindicator > 0.4.0 is needed to enable appindicator."
+        USE_UNITY='N'
       else
-        GTKINC=`pkg-config --cflags $GTK appindicator-0.1`
-        GTKLDFLAGS=`pkg-config --libs $GTK appindicator-0.1`
+        USE_UNITY='Y'
+        echo "found."
+        UNITY_INC="-I/usr/include/libappindicator-0.1"
+        GTKINC=`pkg-config --cflags $GTK $APPINDICATOR`
+        GTKLDFLAGS=`pkg-config --libs $GTK $APPINDICATOR`
       fi
     fi
   fi
@@ -260,7 +343,7 @@ fi
 
 # --- QT3 START ---
 QT_IM='N'
-QT_IM_DIR=/usr/$LIB/qt3/plugins/inputmethods
+QT_IM_DIR=/qt3/plugins/inputmethods
 echo -n ".... Testing Qt 3.x      :  "
 pkg-config --libs qt-mt > /dev/null 2> /dev/null
 if [ $? = 0 ]; then
@@ -278,7 +361,7 @@ if [ "$QT_IM" = "Y" ]; then
     else
 		  if [ ! -x "$QT3_MOC_PATH" ]; then
 				echo "not found, cannot find \"moc\" tool for Qt 3.x."
-				echo "Hint: use the --qt3-moc-path option."
+				echo "Hint: use the --qt3-moc-path option. abort!"
 				exit 1
 		  fi
         echo "found."
@@ -290,7 +373,7 @@ fi
 
 # --- QT4 START ---
 QT4_IM='N'
-if [ -z "$QT4_IM_DIR" ]; then QT4_IM_DIR=/usr/$LIB/qt4/plugins/inputmethods; fi
+if [ -z "$QT4_IM_DIR" ]; then QT4_IM_DIR=/qt4/plugins/inputmethods; fi
 
 echo -n ".... Testing Qt 4.x      :  "
 pkg-config --libs QtCore QtGui > /dev/null 2> /dev/null
@@ -309,7 +392,7 @@ if [ "$QT4_IM" = "Y" ]; then
     else
 		  if [ ! -x "$QT4_MOC_PATH" ]; then
 				echo "not found, cannot find \"moc\" tool for Qt 4.x."
-				echo "Hint: use the --qt4-moc-path option."
+				echo "Hint: use the --qt4-moc-path option. abort!"
 				exit 1
 		  fi		  
         echo "found."
@@ -381,7 +464,6 @@ mandir=$datadir/man
 libdir=$prefix/$LIB
 includedir=$prefix/include
 optdir=/opt
-HIME_VERSION=`cat VERSION.hime`
 
 BUILD_MODULE='N'
 if [ "$USE_ANTHY" = 'Y' ] || [ "$USE_CHEWING" = 'Y' ]; then
@@ -389,7 +471,7 @@ if [ "$USE_ANTHY" = 'Y' ] || [ "$USE_CHEWING" = 'Y' ]; then
 fi
 
 if [ -z "$CFLAGS" ]; then
-  OPTFLAGS="-Wall -Os"
+  OPTFLAGS="-Wall"
 else
   OPTFLAGS="$CFLAGS"
 fi
@@ -408,6 +490,7 @@ echo "CCX=$CC" >> config.mak
 echo "CXX=$CXX" >> config.mak
 echo "CCLD=$CC" >> config.mak
 echo "MAKE=$MAKE" >> config.mak
+echo "GTK=$GTK" >> config.mak
 echo "GTKINC=$GTKINC" >> config.mak
 echo "prefix=$prefix" >> config.mak
 echo "bindir=\$(DESTDIR)$bindir" >> config.mak
@@ -422,7 +505,6 @@ echo "himelibdir=\$(libdir)/hime" >> config.mak
 echo "includedir=\$(DESTDIR)$includedir" >> config.mak
 echo "LDFLAGS=-Wl,--as-needed -lX11 -lm" >> config.mak
 echo "LDFLAGS+=$GTKLDFLAGS -lX11 -ldl" >> config.mak
-echo "HIME_VERSION=$HIME_VERSION" >> config.mak
 echo "HIME_TABLE_DIR=\$(datadir_r)/hime/table" >> config.mak
 echo "HIME_OGG_DIR=\$(datadir_r)/hime/ogg" >> config.mak
 echo "HIME_TABLE_DIR_i=\$(datadir)/hime/table" >> config.mak
@@ -437,9 +519,13 @@ echo "HIME_ICON_DIR_i=\$(datadir)/pixmaps/hime" >> config.mak
 echo "HIME_BIN_DIR=\$(bindir_r)" >> config.mak
 echo "FREEBSD=$FREEBSD" >> config.mak
 echo "QT_IM=$QT_IM" >> config.mak
-echo "QT_IM_DIR=$QT_IM_DIR" >> config.mak
+echo "QT_IM_DIR=\$(libdir)$QT_IM_DIR" >> config.mak
 echo "QT4_IM=$QT4_IM" >> config.mak
-echo "QT4_IM_DIR=$QT4_IM_DIR" >> config.mak
+if [ -z "$QT4_IM_DIR_CUSTOM" ]; then
+	echo "QT4_IM_DIR=\$(libdir)$QT4_IM_DIR" >> config.mak
+else
+	echo "QT4_IM_DIR=\$(DESTDIR)$QT4_IM_DIR_CUSTOM" >> config.mak
+fi
 echo "QT3_MOC_PATH=$QT3_MOC_PATH" >> config.mak
 echo "QT4_MOC_PATH=$QT4_MOC_PATH" >> config.mak
 echo "QT3_QMAKE_PATH=$QT3_MOC_PATH" | sed 's/moc/qmake/' >> config.mak
